### ISSUE TITLE
Uncaught (in promise) TypeError: keys is not a function at setup (index.vue:18:1) in Vue 3 app

### ISSUE THREAD

**Issue by kathirr007** [kimamula/ts-transformer-keys#87] opened 2022-10-20 18:40 UTC
Hi @kimamula,

First of all, thank you for this handy package. I'm trying to use this for my project where I need to extract the values from the API response and use only a few props to create the payload for update API. For this, I need something like this package. But unfortunately, it's giving the error **Uncaught (in promise) TypeError: keys is not a function**. I'm using the project setup with **Vue 3, Typescript 4.7.4, Vite 3.0.4**

My setup:
- **Vue - 3.2.37**
- **Typescript - 4.7.4**
- **ts-node  - 10.9.1**
- **ttypescript  - 1.5.3**
- **Vite** - for tooling

This is my tsconfig.json:
![image](https://user-images.githubusercontent.com/13422232/197030825-ed663d90-f5d0-416b-a7b0-db09d7f76f09.png)

And this is where I'm trying to use as given in the example to check:
![image](https://user-images.githubusercontent.com/13422232/197030655-135ce9bf-1fb8-44e9-b39b-5e3f2421b569.png)

As you can see there is no type error when I'm calling the **keys** function. But, still getting the error while checking in browser.

Error screenshot:
![image](https://user-images.githubusercontent.com/13422232/197030381-fbcd0f36-d393-4820-a9d8-759fb5fa741d.png)

Any help would be greatly appreciated.

Thank you in advance.

**Comment by kimamula** [comment] 2022-11-21 09:34
Hi @kathirr007, sorry for not replying earlier. I think this is because Vite doesn't support TypeScript transformers. Please see this [comment](https://github.com/kimamula/ts-transformer-keys/issues/76#issuecomment-1166687189).

**Comment by kimamula** [comment] 2022-11-21 09:35
Duplicate of #76

**Closed** 2022-11-21 09:35 UTC
